// <auto-generated>
// This file is part of the Kjede project.
// </auto-generated>
namespace Kjede.Lexer.Logic.Tests;

/// <summary>
/// Placeholder.
/// </summary>
public class Tests
{
    /// <summary>
    /// Placeholder.
    /// </summary>
    [Test]
    public void Test1()
    {
        Dummy dummy = new ();
        Assert.Throws<NotImplementedException>(dummy.Foo);
        Assert.Pass();
    }
}
