// <auto-generated>
// This file is part of the Kjede project.
// </auto-generated>
namespace Kjede.Lexer.Logic;

using Api;

/// <inheritdoc />
public class Dummy : IDummy
{
    /// <inheritdoc />
    public void Foo()
    {
        throw new NotImplementedException();
    }
}