// <auto-generated>
// This file is part of the Kjede project.
// </auto-generated>
namespace DefaultNamespace;

/// <summary>
///  Dummy interface.
///  </summary>
public interface IDummy
{
    /// <summary>
    /// Dummy method.
    /// </summary>
    public void Foo();
}