name: Run Stryker.NET with Dashboard Reporting

on:
  pull_request:
    branches: [ main ]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: dotnet tool restore

      - name: Run Stryker.NET against Repository
        uses: lyndychivs/dotnet-stryker-action@v1.5
        with:
          configurationFile: "stryker-config.json"
          dashboardApiKey: ${{ secrets.STRYKER_DASHBOARD }}
